<?php

/* RHP / Tribe Events Fields */
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_event-settings',
		'title' => 'Event Settings',
		'fields' => array (
			array (
				'key' => 'field_53dabb1d47eaf',
				'label' => 'Dates',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53dabb2847eb0',
				'label' => 'Display on Date',
				'name' => '',
				'type' => 'message',
				'message' => 'Use the built-in <a href="http://en.support.wordpress.com/posts/schedule-a-post/" target="_blank">Schedule a Post</a> feature to hide an Event until a specific date and time.',
			),
			array (
				'key' => 'field_546ce25712485',
				'label' => 'Performance Date',
				'name' => 'rhp_event_start_date',
				'type' => 'date_time_picker',
				'required' => 1,
				'show_date' => 'true',
				'date_format' => 'm/d/y',
				'time_format' => 'h:mm tt',
				'show_week_number' => 'false',
				'picker' => 'slider',
				'save_as_timestamp' => 'true',
				'get_as_timestamp' => 'false',
			),
			array (
				'key' => 'field_546ce2bf12487',
				'label' => 'All Day Event?',
				'name' => 'rhp_event_all_day',
				'type' => 'true_false',
				'instructions' => 'When selected the Event will display as a full day event without start or end time information.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_546ce27612486',
				'label' => 'End Date',
				'name' => 'rhp_event_end_date',
				'type' => 'date_time_picker',
				'instructions' => 'Optional, defaults to midnight of the Performance Date. After this time the event will be displayed as a Past Event.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_546ce2bf12487',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'show_date' => 'true',
				'date_format' => 'm/d/y',
				'time_format' => 'h:mm tt',
				'show_week_number' => 'false',
				'picker' => 'slider',
				'save_as_timestamp' => 'true',
				'get_as_timestamp' => 'false',
			),
			array (
				'key' => 'field_53dabb8147eb1',
				'label' => 'On Sale Date',
				'name' => 'rhp_event_on_sale_date',
				'type' => 'date_time_picker',
				'show_date' => 'true',
				'date_format' => 'm/d/y',
				'time_format' => 'h:mm tt',
				'show_week_number' => 'false',
				'picker' => 'slider',
				'save_as_timestamp' => 'true',
				'get_as_timestamp' => 'false',
			),
			array (
				'key' => 'field_53dabbb247eb2',
				'label' => 'Off Sale Date',
				'name' => 'rhp_event_off_sale_date',
				'type' => 'date_time_picker',
				'instructions' => 'Remove the link to effectively make this show visible with with no Call to Action.',
				'show_date' => 'true',
				'date_format' => 'm/d/y',
				'time_format' => 'h:mm tt',
				'show_week_number' => 'false',
				'picker' => 'slider',
				'save_as_timestamp' => 'true',
				'get_as_timestamp' => 'false',
			),
			array (
				'key' => 'field_53dab8c647eab',
				'label' => 'Details',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_547f4a41ad52d',
				'label' => 'CTA Link',
				'name' => 'rhp_event_cta_url',
				'type' => 'text',
				'instructions' => 'This is most commonly the link to purchase tickets for this event.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5554c8475eff4',
				'label' => 'Secondary CTA Button Text',
				'name' => 'secondary_cta_button_text',
				'type' => 'text',
				'instructions' => 'This creates a secondary CTA button below the primary CTA button.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5554c85a5eff6',
				'label' => 'Secondary CTA Link',
				'name' => 'secondary_cta_button_link',
				'type' => 'text',
				'instructions' => 'You will need to link the Secondary CTA for it to display.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_546ce41e134db',
				'label' => 'Event Cost',
				'name' => 'rhp_event_cost',
				'type' => 'text',
				'instructions' => 'Descriptive text is OK: "$10", "ADV $5 / DOS $10", "Free with Wristband"',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54da835500784',
				'label' => 'List as Free Show',
				'name' => 'rhp_event_free_show',
				'type' => 'true_false',
				'instructions' => 'Check the box to display this event with the Free Show CTA.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_54da892821c85',
				'label' => 'Sold Out',
				'name' => 'rhp_event_sold_out',
				'type' => 'true_false',
				'instructions' => 'Check the box to display this event with the unlinked Sold Out CTA.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53dab90947eac',
				'label' => 'Tagline',
				'name' => 'rhp_event_tagline',
				'type' => 'text',
				'instructions' => 'Appears above the event header.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53dab93d47ead',
				'label' => 'Subheader',
				'name' => 'rhp_event_subheader',
				'type' => 'text',
				'instructions' => 'Appears below the event header.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53dab9ba47eae',
				'label' => 'Notes',
				'name' => 'rhp_event_notes',
				'type' => 'textarea',
				'instructions' => 'Used for general show information, restrictions, doors times, etc. This is displayed on all views of the Event.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 2,
				'formatting' => 'html',
			),
			array (
				'key' => 'field_53dbb5dca5c12',
				'label' => 'Social',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53dbb61ca5c13',
				'label' => 'Facebook Event URL',
				'name' => 'rhp_event_facebook_event_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53dabc4b47eb4',
				'label' => 'Advanced',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53dabc5247eb5',
				'label' => 'Call to Action Overrides',
				'name' => '',
				'type' => 'message',
				'message' => 'You can change the default labels used in Calls to Action by entering text in the label fields here.	When left blank they will use the values in the <a href="/wp-admin/edit.php?post_type=tribe_events&page=rhp-events-settings" target="_blank">Rockhouse Events Settings</a>.',
			),
			array (
				'key' => 'field_53dabcfb47eb6',
				'label' => 'Hide the Call to Action',
				'name' => 'rhp_event_hide_cta',
				'type' => 'true_false',
				'instructions' => 'Don\'t display a CTA of any kind.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53dabd1c47eb7',
				'label' => 'CTA Label: Free Show',
				'name' => 'rhp_event_cta_label_free_show',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53dabd4e47eb8',
				'label' => 'CTA Label: Sold Out',
				'name' => 'rhp_event_cta_label_sold_out',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53dabd6147eb9',
				'label' => 'CTA Label: Coming Soon',
				'name' => 'rhp_event_cta_label_coming_soon',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53dabd7447eba',
				'label' => 'CTA Label: On Sale',
				'name' => 'rhp_event_cta_label_on_sale',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53dabd8647ebb',
				'label' => 'CTA Label: Off Sale',
				'name' => 'rhp_event_cta_label_off_sale',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'tribe_events',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'send-trackbacks',
			),
		),
		'menu_order' => 1,
	));
}

