<?php

/* RHP / Tribe Events - Event Series Category Fields */
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_event-series-category-page',
		'title' => 'Event Series Category Page',
		'fields' => array (
			array (
				'key' => 'field_55b8f794925eb',
				'label' => 'Series CTA Link',
				'name' => 'rhp_series_cta_url',
				'type' => 'text',
				'instructions' => 'Used for the CTA to link externally for the entire Event Series.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55b2907fd2703',
				'label' => 'Featured Image',
				'name' => 'rhp_series_page_image',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55b29098d2704',
				'label' => 'Series Info',
				'name' => 'rhp_series_page_description',
				'type' => 'wysiwyg',
				'instructions' => 'This is displayed as the primary content for the overview page of this Event Series.	Please note that the Description field above is not used.',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_55b290c4d2705',
				'label' => 'First Performance Date',
				'name' => 'rhp_series_start_date',
				'type' => 'date_time_picker',
				'show_date' => 'true',
				'date_format' => 'm/d/y',
				'time_format' => 'h:mm tt',
				'show_week_number' => 'false',
				'picker' => 'slider',
				'save_as_timestamp' => 'true',
				'get_as_timestamp' => 'false',
			),
			array (
				'key' => 'field_55b290ecd2706',
				'label' => 'Last Performance Date',
				'name' => 'rhp_series_end_date',
				'type' => 'date_time_picker',
				'show_date' => 'true',
				'date_format' => 'm/d/y',
				'time_format' => 'h:mm tt',
				'show_week_number' => 'false',
				'picker' => 'slider',
				'save_as_timestamp' => 'true',
				'get_as_timestamp' => 'false',
			),
			array (
				'key' => 'field_55b2912ed2707',
				'label' => 'Minimum Price',
				'name' => 'rhp_series_min_price',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55b29148d2708',
				'label' => 'Maximum Price',
				'name' => 'rhp_series_max_price',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55bfa6bff2184',
				'label' => 'Etix Event ID',
				'name' => 'rhp_series_etix_event_id',
				'type' => 'number',
				'instructions' => 'Links this series to the Etix Event Series.	Please do not change this field.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'tribe_events_cat',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
